### PR TITLE
fix a whitespace bug in the armor regex

### PR DESCRIPTION
**Pull request by oconnor663**
This was caught by @scolby33.

r? @maxtaco @AMarcedone

### CODE REVIEW

**Comment by oconnor663** [comment]
@maxtaco could you `git pull` the relevant repos on our webservers when you get a chance?

**Comment by maxtaco** [comment]
hmm sure..  there's like a symlink or something?  i forgot.  i'll look into it tomorrow. thank you @oconnor663 !

**Comment by AMarcedone** [comment]
Cool! I had noticed it too, it was on my todo list :)

As for the server, I suspect he means we should update the vendored version of saltpack in our other repos...

**Comment by maxtaco** [comment]
in this case, we need to pull the saltpack go module, which is linked into
the saltpack.org node library via symlink.  i think it worked

**Pull request merged**
