### PR TITLE
Fix regex in spec

### PR DESCRIPTION
**Pull request by jscissr**
The parentheses were wrong. The *or* operator `|` needs to be inside the parentheses.

By the way, you can visualize regexes on https://www.debuggex.com

### CODE REVIEW

**Comment by maxtaco** [comment]
Cc: @oconnor663  please check it out

**Comment by oconnor663** [comment]
Both versions seem to work in Go. Is Go unusually permissive about this. I'm trying other languages to get a better idea.

**Comment by jscissr** [comment]
You might need to add start and end anchors to the regex:

    ^ ... $

**Comment by oconnor663** [comment]
Ok so Python requires your changes to work correctly, but Go and Rust both seem to work fine with the current version. Can anyone explain why that is? I don't know enough about regexes :p

**Comment by jscissr** [comment]
I see, the thing is that the anchors are also taken by the or operator. If you add parens between the anchors:

    ^( ... )$

It shouldn't work anymore. The problem with the previous regex is not that it fails on valid strings, but that it allows invalid strings. For example `FOOBAR SIGNED MESSAGE` is accepted.

**Comment by oconnor663** [comment]
Got it, yep, now I'm seeing the difference. Thanks for your help!

**Pull request merged**
